name: Welcome New Contributor

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    if: github.event.pull_request.author_association == 'FIRST_TIMER'
    steps:
      - name: Greet the contributor
        run: echo "👋 Welcome to the project! Thank you for your first pull request!"
